name: gocd-cli setup
description: installs and caches the gocd-cli and yaml plugin
runs:
  using: composite
  steps:
    - name: setup vars
      id: vars
      shell: bash
      run: python3 -uS ${{ github.action_path }}/bin/setup-gocd-cli vars

    - name: cache gocd-cli
      id: cache
      uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7  # v3.0.11
      with:
        path: ${{ steps.vars.outputs.gocd-cli-dir }}
        key: ${{ steps.vars.outputs.cache-key }}

    - name: install gocd-cli
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: python3 -uS ${{ github.action_path }}/bin/setup-gocd-cli install
